M48
; DRILL file {KiCad 9.0.7} date 2026-03-04T21:31:58-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-04T21:31:58-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0433
%
G90
G05
T1
X5.1783Y-1.1717
X5.1783Y-1.3992
T2
X5.7539Y-2.1358
X5.7549Y-1.8209
T3
X5.676Y-2.4807
M30
